import Foundation

struct DeedSource {
    static let allDeeds: [String] = [
        "Apply today to donate blood, share medicals, save health of others",
        "Be patient in a stressful situation",
        "Be the reason someone smiles today",
        "Buy a plant or a tree or plant it yourself - to save the planet",
        "Call a loved one",
        "Call an old friend to check how he is",
        "Call somebody in a foreign country so they know they are not forgotten",
        "Call your mother/father/sister/brother just to check on them",
        "Carpool with coworkers to reduce emissions",
        "Celebrate someone’s achievements sincerely",
        "Check in on a sick friend / call somebody who is ill",
        "Check in with a friend who lives alone",
        "Compliment a parent on their parenting",
        "Compliment a stranger",
        "Compliment someone’s outfit or style",
        "Cook a meal for somebody or give him supplies",
        "Create or share helpful online tutorials or guides",
        "Donate books to a library, school, or somebody who will have use of it",
        "Donate clothes you no longer use",
        "Donate money or feed the poor",
        "Donate old clothes",
        "Donate old tech devices to those in need",
        "Donate unused item to somebody who will rather use it",
        "Educate yourself or others about social injustice",
        "Encourage others to keep learning and growing",
        "Encourage others to treat everyone with respect",
        "Express appreciation for someone's goodness towards you",
        "Express gratitude to people around you",
        "Feed an animal / give water / or cuddle it",
        "Fix something that's broken - recycle, not throw away",
        "Forgive someone you've been holding a grudge against",
        "Give a compliment to a complete stranger",
        "Give a present to a friend or your colleague",
        "Give sincere feedback on someone’s work",
        "Give someone a genuine smile to brighten their day",
        "Give someone a hug",
        "Give someone a ride or share the same transportation",
        "Go through old memories together with someone",
        "Help a coworker with a project / student with their studies",
        "Help a friend through a difficult time",
        "Help a neighbor",
        "Help an elderly person or neighbor with their daily things",
        "Assist someone struggling with their task",
        "Help someone feel appreciated and valued if he/she doesn’t feel it",
        "Help someone feel included and valued in a group/society",
        "Help someone find a job or get internship",
        "Help someone improve their resume or LinkedIn profile",
        "Help someone with their daily tasks",
        "Help with household chores without being asked",
        "Hold the door",
        "Join an online support group and share kind words",
        "Leave a generous tip for a server",
        "Leave a kind note in a public place like a library book or mirror",
        "Leave a positive online review for a small local business",
        "Let someone go ahead of you",
        "Let someone merge in traffic with a smile",
        "Listen actively to someone who needs to talk about their problems",
        "Offer a genuine apology even if other person did wrong",
        "Offer a helping hand to someone in need",
        "Offer emotional support to a person who needs it",
        "Offer to babysit for free so someone can take a break",
        "Organize a mini cleanup in your local area",
        "Pay for somebody's coffee",
        "Pick flowers",
        "Pick up litter",
        "Pick up the trash in your neighborhood / in nature",
        "Plan a surprise for someone you love",
        "Plant a flower in a public space or gift one to someone",
        "Pray or wish someone well from your heart",
        "Publicly recognize someone's hard work",
        "Recommend a free learning resource to someone trying to grow",
        "Recommend someone a freelance job if they need",
        "Recycle plastic bottles or cardboard boxes",
        "Recycle trash",
        "Report harmful or fake content",
        "Respectfully stand up for someone being mistreated",
        "Sincerely thank someone for their kindness or service",
        "Compliment someone who may feel unseen or lonely",
        "Send a deep message from heart to a loved one",
        "Send a positive text",
        "Share a compliment",
        "Share a productivity tip or self-care habit with someone",
        "Share excess garden vegetables or herbs with neighbors",
        "Share positive messages or quotes on social media",
        "Write down one habit you want to improve and take the first step",
        "Share snacks with people from narrow circle/colleagues",
        "Share your favorite inspirational quote with friends",
        "Share your favorite recipe with someone",
        "Show patience and understanding in difficult conversations",
        "Smile genuinely at someone who looks like they need it",
        "Smile to a kid or buy him/her a candy",
        "Speak up when you witness unfair treatment or bullying",
        "Spend time playing with or reading to a child",
        "Spend uninterrupted quality time with a loved one",
        "Start separating recyclables, create a labeled recycling bin in your home",
        "Support a cause",
        "Support a charity through a donation link on social app",
        "Support a familiar person’s small business",
        "Support someone in their dreams and goals",
        "Teach a child something useful or teach new foreign words",
        "Teach someone a new skill or share wisdom with them",
        "Teach someone how to use a helpful app or tool",
        "Text a friend",
        "Turn off your phone during time with loved ones",
        "Volunteer at a local shelter or food bank",
        "Walk today instead of polluting earth with more gasoline",
        "Wave at someone",
        "Write a gratitude note to somebody",
        "Write a kind thing",
        "Write a letter to your local representative advocating for a cause you care about",
        "Write an inspirational note to someone",
        "Write or speak publicly against injustice",
        "Forgive yourself for a mistake you’ve been holding",
        "Treat yourself to rest and peace",
        "Speak about somebody positively aloud",
        "Unfollow toxic accounts and replace them with inspiring ones",
        "Spend one day without gossiping or judging anyone",
        "Switch 15 minutes of screen time for a walk or quiet time",
        "Start a ‘no phone during meals’ rule and invite others to join",
        "Encourage someone else to break a bad habit"
    ]
}
